type Movie {
  id: ID!
  title: String!
  year: Int!
  popularity: Int!
  description: String!
  contentRating: String!
  movieLength: Float!
  rating: Float!
  createdAt: String!
  trailer: String!
  imageUrl: String!
  release: String
  plot: String!
  banner: String!
  type: String!
  genres: [Genre!]
  keywords: [Keyword!]
}

enum MoviesSort {
  title
  popularity
  release
  rating
}
