type Mutation {
  register(name: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  logout: Boolean!
  refresh(refreshToken: String!): AuthPayload!
  addToWatchlist(id: ID!): String!
  removeFromWatchlist(id: ID!): String!
}
